### ISSUE TITLE
`convox exec` errors

### ISSUE THREAD

**Issue by frsechet** [convox/rack#1374]
Hi,

noticed a few errors with `convox exec` commands:

1. When I exec into a container that doesn't exist, I will get the following and I'm not able to ctrl+C out of it. It just hangs and I can only close my terminal window.
    ```
    $ convox exec 3c1077fe71ac bash
    ERROR: could not find process
    ```

2. The following gives a weird error:
    ```
    $ convox exec e01bc6dcc66a bash
    root@52597e23b96b:/app# ^C
    root@52597e23b96b:/app# exit
    ERROR: %!(EXTRA int=130)
    ```

```
$ convox -v
client: 20161028232500
server: 20161026221456
```

**Comment by ddollar** [comment]
Should be fixed now

**Comment by frsechet** [comment]
Nope. #1 is still there in client version `20170103233602`.

`convox exec xxxxxxxxxx bash -a myapp` (where `xxxxxxxxxx` doesn't exist for this app) still hangs

**Comment by ddollar** [comment]
Looks like this is captured in #1328
